site_name: lilota
site_url: https://tobiasroessler.github.io/lilota/
theme:
  name: material
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.snippets
nav:
  - lilota: index.md
  - User Guide:
    - Lilota is simple: lilota-is-simple.md
    - Task registration: task-registration.md
    - Shutdown: shutdown.md
    - Database: database.md
  - Reference:
    - Lilota: lilota-reference.md