"""initial schema

Revision ID: b4186f417ece
Revises:
Create Date: 2026-04-09 22:27:43.370238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4186f417ece"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lilota_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("logger", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("process", sa.String(length=64), nullable=True),
        sa.Column("thread", sa.String(length=64), nullable=True),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lilota_node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('idle', 'starting', 'running', 'stopping', 'stopped', 'crashed', 'dead')",
            name="lilota_note_status_check",
        ),
        sa.CheckConstraint(
            "type IN ('scheduler', 'worker')", name="lilota_note_type_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lilota_node_leader",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lilota_task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("retried_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_task_id", sa.Uuid(), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("start_date_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input", sa.JSON(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("locked_by", sa.Uuid(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('created', 'scheduled', 'running', 'completed', 'failed', 'expired', 'cancelled')",
            name="lilota_task_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_get_next_task", "lilota_task", ["status", "run_at"], unique=False
    )
    op.create_index(
        "idx_retryable_tasks",
        "lilota_task",
        ["retried_at", "status", "run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lilota_task_retried_at"), "lilota_task", ["retried_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lilota_task_retried_at"), table_name="lilota_task")
    op.drop_index("idx_retryable_tasks", table_name="lilota_task")
    op.drop_index("idx_get_next_task", table_name="lilota_task")
    op.drop_table("lilota_task")
    op.drop_table("lilota_node_leader")
    op.drop_table("lilota_node")
    op.drop_table("lilota_log")
    # ### end Alembic commands ###
